#!/bin/bash
echo "[*] Generating: USERDATA"
mkdir -p "$USERDATA"
echo "[*] Generating: Library"
echo "[*] Generating: Developer"
mkdir -p "$DATA/Library/Developer"
echo "[*] Generating: init"
mkdir -p "$DATA/init"
echo "[*] Generating: nvram"
mkdir -p "$DATA/nvram"
echo "[*] Generating: mount"
mkdir -p "$DATA/mount"
echo "[*] Generating: config"
mkdir -p "$DATA/config"
echo "[*] Done."
