#!/bin/bash

# 프로젝트 루트 디렉토리로 이동
cd "$(dirname "$0")/../"

# Source 폴더에서 System 폴더로 파일 복사 후 불필요한 파일 삭제
rm -rf "System"
cp -r "Source" "System"
rm -rf "System/.git" "System/.gitattributes" "System/.gitignore" "System/README.md" "System/compileandrun"


# .sh, .hxe 확장자를 가진 파일 처리
for ext in sh hxe; do
    # 해당 확장자를 가진 파일 검색
    LIST=$(find "System" -name "*.$ext")

    # 검색된 파일 이름에서 확장자 제거 후 실행 권한 부여 및 이름 변경
    echo "$LIST" | while read line; do
		chmod +x "$line"
		if [[ "$ext" == "sh" ]]; then	
			mv "$line" "$(echo "$line" | cut -f 1 -d '.')"
		fi
		
    done
done

# .framework와 .init에서 exec.sh 파일 이름 변경
find "System" -path "*/.framework/exec.sh" -exec sh -c 'chmod +x "$0" && mv "$0" "$(dirname "$0")/exec"' {} \;
find "System" -path "*/.init/exec.sh" -exec sh -c 'chmod +x "$0" && mv "$0" "$(dirname "$0")/exec"' {} \;


# 실행 인수에 따라 스크립트 종료 또는 실행 파일 실행
if [[ "$1" == "norun" ]]; then
    exit 0
elif [[ "$1" == "pkg" ]]; then
    tar -czpf "image.tar.gz" --exclude=".*" --exclude="__MACOSX" "System"
    exit 0
else
    if [[ "$1" == "--firm" ]]; then
        shift
        "$PWD/System/boot/firm" "$@"
    else
        "$PWD/System/boot/init" "$@"
    fi
fi
