#!/bin/bash

# 프로젝트 루트 디렉토리로 이동
cd "$(dirname "$0")"

echo "Making installer target..."
mkdir ../Installer
./mksystem norun

echo "Making packages..."
cp -r "Installer" ../System/
./mkpkgs

echo "Cleaning up..."
find ../System -mindepth 1 -maxdepth 1 -type d -not -name "Installer" -exec rm -rf {} \;
echo "Installing minimum packages for installer..."
echo "Extracting kernel..."
tape install ../System/Installer/packages/hermes-kernel-2x-* ../System/Installer/packages/liteos-* ../System/Installer/packages/hermes-services-core-* ../System/Installer/packages/core-binaries-* --target=../Installer --force
# echo "Extracting hermes-services-core..."
# tape install --target=../Installer --force
# echo "Extracting core binaries..."
# tape install ../System/Installer/packages/core-binaries-* --target=../Installer --force
# echo "Extracting liteos..."
# tape install  --target=../Installer --force

echo "Generating installer..."
cp -r ../System/Installer ../Installer/System/
echo "export HERMESNAME=\"HermesOS Installation Media\"" >> ../Installer/System/boot/llhooks.ll
echo "export BOOTARGS=\"verbose liteos\"" >> ../Installer/System/boot/llhooks.ll
echo "cp \"\$SYSTEM/AUTOCONFIG\" \"\$ROOTFS/\"" >> ../Installer/System/boot/llhooks.ll
echo "rm -rf \"\$DATA\" \"\$LIBRARY\" 2>/dev/null" >> ../Installer/System/boot/llhooks.ll
chmod +x ../Installer/System/Installer/bin/*

echo "Removing unnecessary files..."
rm -rf ../System

echo "Moving files..."
mv ../Installer/System ../System
mv ../System/Installer/AUTOCONFIG ../System/
rm -rf ../Installer

echo "Generating into packages..."
if [[ -f "../image.tar.gz" ]]; then
    mv ../image.tar.gz ../image.tar.gz.bak
fi
if [[ -f "../installer.tar.gz" ]]; then
    rm ../installer.tar.gz
fi
./mksystem nosync pkg
mv ../image.tar.gz ../installer.tar.gz
if [[ -f "../image.tar.gz.bak" ]]; then
    mv ../image.tar.gz.bak ../image.tar.gz
fi
