#!/bin/bash

# 프로젝트 루트 디렉토리로 이동
cd "$(dirname "$0")"

echo "Making installer target..."
mkdir ../Installer
./mksystem norun

echo "Making packages..."
cp -r "Installer" ../System/
./mkpkgs

echo "Cleaning up..."
find ../System -mindepth 1 -maxdepth 1 -type d -not -name "Installer" -exec rm -rf {} \;
echo "Installing minimum packages for installer..."
echo "Extracting kernel..."
tape install ../System/Installer/packages/hermes-kernel-2x-* ../System/Installer/packages/liteos-* ../System/Installer/packages/hermes-services-core-* ../System/Installer/packages/core-binaries-* --target=../Installer --force
# echo "Extracting hermes-services-core..."
# tape install --target=../Installer --force
# echo "Extracting core binaries..."
# tape install ../System/Installer/packages/core-binaries-* --target=../Installer --force
# echo "Extracting liteos..."
# tape install  --target=../Installer --force

echo "Generating installer..."
cp -r ../System/Installer ../Installer/System/
echo "export BOOTARGS=\"verbose\"" >> ../Installer/System/boot/partitions.hdp
echo "cp \"\$SYSTEM/AUTOCONFIG\" \"\$ROOTFS/\"" >> ../Installer/System/boot/partitions.hdp
chmod +x ../Installer/System/Installer/bin/*

echo "Removing unnecessary files..."
rm -rf ../System

echo "Moving files..."
mv ../Installer/System ../System
cp ../System/Installer/AUTOCONFIG ../System/
rm -rf ../Installer

echo "Generating into packages..."
./mksystem nosync pkg
