#!/bin/bash
function sys_log() {
	d_out "$LIBRARY/Logs/"
	f_out "$LIBRARY/Logs/$LOGFILENAME" "$(date '+%Y-%m-%d %H:%M:%S') [ $1 ] $2"
}

function bootArgumentHas() {
	if [[ ! -z "$(echo "$BOOTARGS" | grep "$1")" ]]; then
		sys_log "internal-func" "Boot argument contains $1."
		echo 1
	else
		sys_log "internal-func" "Boot argument does not contain $1."
		echo 0
	fi
}

function verbose() {
	if [[ $(bootArgumentHas "verbose") == 1 ]]; then
		sc_out "$1"
	fi
}

function leaveSystem() {
	sys_log "internal-func" "Leaving system..."
	if [[ $(bootArgumentHas "no-cache-reset") == 0 ]]; then
		d_del "$CACHE" 2>/dev/null
	fi
	exit 0
}

function error() {
	clear
	sc_out "==========SYSTEM FATAL EXCEPTION=========="
	sc_out -e "$1"
	sc_out "=========================================="
	sys_log "ErrorHandler" "There was an error reported."
	sys_log "ErrorHandler" "$1"
	# if [[ ! -z "$(LITE_HELP)" ]]; then
	# 	sys_log "ErrorHandler" "LiteOS present in memory. Calling main..."
	# 	liteos_main
	# else
		# sys_log "ErrorHandler" "LiteOS is not uploaded in memory. Leaving system..."
		leaveSystem
	# fi
}

export -f bootArgumentHas
export -f verbose
export -f leaveSystem
export -f sys_log
export -f error
export LOGFILENAME="$(date '+%Y%m%d%H%M%S')"
