#!/bin/bash
function sys_log() {
	mkdir -p "$LIBRARY/Logs/"
	echo "$(date '+%Y-%m-%d %H:%M:%S') [ $1 ] $2" >> "$LIBRARY/Logs/$LOGFILENAME"
}

function bootArgumentHas() {
	if [[ ! -z "$(echo "$BOOTARGS" | grep "$1")" ]]; then
		sys_log "internal-func" "Boot argument contains $1."
		echo 1
	else
		sys_log "internal-func" "Boot argument does not contain $1."
		echo 0
	fi
}

function verbose() {
	if [[ $(bootArgumentHas "verbose") == 1 ]]; then
		echo -e "$1"
	fi
}

function leaveSystem() {
	sys_log "internal-func" "Leaving system..."
	if [[ $(bootArgumentHas "no-cache-reset") == 0 ]]; then
		rm -rf "$CACHE" 2>/dev/null
	fi
	trap - INT
	unset -f sysreset 2>/dev/null
	return 0
}

function error() {
	clear
	echo "==========SYSTEM FATAL EXCEPTION=========="
	echo -e "$1"
	echo "=========================================="
	sys_log "ErrorHandler" "There was an error reported."
	sys_log "ErrorHandler" "$1"
	if [[ ! -z "$(LITE_HELP)" ]]; then
		sys_log "ErrorHandler" "LiteOS present in memory. Calling main..."
		liteos_main
	else
		sys_log "ErrorHandler" "LiteOS is not uploaded in memory. Leaving system..."
		leaveSystem
		exit 0
	fi
}

export -f bootArgumentHas
export -f verbose
export -f leaveSystem
export -f sys_log
export -f error
export LOGFILENAME="$(date '+%Y%m%d%H%M%S')"
