#!/bin/bash
SPACE="$2/"
BUNDLE="$1"
echo "[*] Profiler version $(<$BUNDLE/sys_version)"
echo "[*] Uploading system profiles to cache space..."
echo "[*] Uploading: sys_name"
cp "$BUNDLE/sys_name" "$SPACE"
echo "[*] Uploading: sys_version"
cp "$BUNDLE/sys_version" "$SPACE"
echo "[*] Uploading: sys_build"
cp "$BUNDLE/sys_build" "$SPACE"
echo "[*] Uploading: sys_architecture"
cp "$BUNDLE/sys_architecture" "$SPACE"
echo "[*] Uploading: sys_manufacture"
cp "$BUNDLE/sys_manufacture" "$SPACE"
echo "[*] Uploading: sys_compatibility"
cp "$BUNDLE/sys_compatibility" "$SPACE"
echo "[*] Uploading: manu_copyright"
cp "$BUNDLE/manu_copyright" "$SPACE"
echo "[*] Uploading: interface_version"
cp "$BUNDLE/interface_version" "$SPACE"
echo "[*] Upload complete."
exit 0