#!/bin/bash
cd "$CORE/functions"
export ALLOC_DATA=""
while read defname
do
	sys_log "loader" "Reading memory allocation data: $defname"
	verbose "[${GREEN}*${C_DEFAULT}] Reading memory allocation data: $defname"
	export SYNC_DEFNAME="$defname"
	source "$CORE/functions/$defname"
	sys_log "loader" "Loaded: $SYNC_DEFNAME"
	verbose "[${GREEN}*${C_DEFAULT}] Loaded: $defname"
	export ALLOC_DATA="$ALLOC_DATA
$SYNC_DEFNAME"
	unset SYNC_DEFNAME
done <<< "$(ls -p | grep -v / | grep ".hfunc")"
sys_log "loader" "Finished reading allocation data."

cd "$CORE/extensions"
export agentlist="$(ls -p | grep -v / | grep ".hxe")" 2>/dev/null
export exitStatus="0"
export EXTENSION_LOADED=""
while read agentname
do
	if [[ ! -z "$agentname" ]]; then
		sys_log "loader" "Loading agent: $agentname"
		verbose "[*] Loading: $agentname"
		"./$agentname"
		export returned=$?
		if [[ "$returned" == 0 ]]; then
			sys_log "loader" "Load success: $agentname"
			verbose "[${GREEN}*${C_DEFAULT}] Load complete."
			export EXTENSION_LOADED="$EXTENSION_LOADED
$agentname"
		elif [[ "$returned" == 1 ]] && [[ "$agentname" == "OSUtility.hxe" ]]; then
			sys_log "loader" "System update completion detected."
			echo -e "${GREEN}System update complete. Please restart the computer.${C_DEFAULT}"
			touch "$BOOTREFUSE"
			exit 0
		elif [[ -f "$BOOTREFUSE" ]]; then
			sys_log "loader" "Boot refused."
			echo "❌"
			verbose "${RED}Boot refused: $(cat "$BOOTREFUSE") ${C_DEFAULT}"
			exit 2
		else
			sys_log "loader" "Agent did not loaded correctly: $agentname"
			verbose "[${YELLOW}!${C_DEFAULT}] $agentname returned exit code $returned."
			error "Agent $agentname returned exit code $returned."
			exit 120
		fi
	fi
done <<< "$agentlist"
sys_log "loader" "Agent loading complete."
