#!/bin/bash
function sc_out() {
	echo -e "$1"
}

function sc_out_nlb() {
	echo -ne "$1"
}

function sc_vid_out() {
	sc_out "$()"
}

export -f sc_out
export -f sc_out_nlb
export -f sc_vid_out
source "$(dirname "$0")/colorprofile"
