#!/bin/bash
cp -r "$1/System/bin" "$2/System/"
cp -r "$1/System/man" "$2/System/"

rm -rf "$2/System/bin/virt"*
rm -rf "$2/System/man/virt"*
rm -rf "$2/System/bin/packager"
rm -rf "$2/System/man/packager"
rm -rf "$2/System/bin/hic"
rm -rf "$2/System/man/hic"
rm -rf "$2/System/bin/lec"
rm -rf "$2/System/man/lec"
rm -rf "$2/System/bin/sudo"
rm -rf "$2/System/man/sudo"
rm -rf "$2/System/bin/paths"
