#!/bin/bash
mkdir -p "$2/System/core/extensions"
mkdir -p "$2/System/core/functions"

cp "$1/System/core/loader" "$2/System/core"
cp "$1/System/core/uistart" "$2/System/core"
cp "$1/System/core/osstop" "$2/System/core"

cp "$1/System/core/extensions/AutoDefaultSetup.hxe" "$2/System/core/extensions/"
cp "$1/System/core/extensions/AutoSystemConfigure.hxe" "$2/System/core/extensions/"
cp "$1/System/core/extensions/OSUtility.hxe" "$2/System/core/extensions/"

cp "$1/System/core/functions/CoreFunctions.hfunc" "$2/System/core/functions/"
cp "$1/System/core/functions/Fort.hfunc" "$2/System/core/functions/"
cp "$1/System/core/functions/HardLink.hfunc" "$2/System/core/functions/"
cp "$1/System/core/functions/ISAKit.hfunc" "$2/System/core/functions/"
cp "$1/System/core/functions/KernelProfile.hfunc" "$2/System/core/functions/"
cp "$1/System/core/functions/Language.hfunc" "$2/System/core/functions/"
cp "$1/System/core/functions/Profile.hfunc" "$2/System/core/functions/"
cp "$1/System/core/functions/Quarantine.hfunc" "$2/System/core/functions/"
cp "$1/System/core/functions/InterProcessCommunications.hfunc" "$2/System/core/functions/"
