#!/bin/bash
cp -r "$1/System/sys" "$2/System/"
rm -rf "$2/System/sys/Library/Virtualization"
rm -rf "$2/System/sys/Library/Legacy"
rm -rf "$2/System/sys/Library/Developer"
rm -rf "$2/System/sys/Library/RecoveryOS"
rm -rf "$2/System/sys/Library/tape"
