#!/bin/bash
cp -r "$1/System/sys" "$2/System/"
rm -rf "$2/System/sys/Library/Virtualization"
rm -rf "$2/System/sys/Library/Legacy"

cp -r "$1/System/core" "$2/System/"

# Other core modules
rm -rf "$2/System/core/loader"
rm -rf "$2/System/core/osstop"
rm -rf "$2/System/core/uistart"

# Kernel built in extensions
rm -rf "$2/System/core/extensions/AutoDefaultSetup.hxe"
rm -rf "$2/System/core/extensions/AutoSystemConfigure.hxe"
rm -rf "$2/System/core/extensions/OSUtility.hxe"

rm -rf "$2/System/core/functions/CoreFunctions.hfunc"
rm -rf "$2/System/core/functions/Fort.hfunc"
rm -rf "$2/System/core/functions/HardLink.hfunc"
rm -rf "$2/System/core/functions/ISAKit.hfunc"
rm -rf "$2/System/core/functions/KernelProfile.hfunc"
rm -rf "$2/System/core/functions/Language.hfunc"
rm -rf "$2/System/core/functions/Profile.hfunc"
rm -rf "$2/System/core/functions/Quarantine.hfunc"

mkdir -p "$2/System/bin"
mkdir -p "$2/System/man"
cp "$1/System/bin/packager" "$2/System/bin"
cp "$1/System/man/packager" "$2/System/man"
cp "$1/System/bin/hic" "$2/System/bin"
cp "$1/System/man/hic" "$2/System/man"
# cp "$1/System/bin/lec" "$2/System/bin"
# cp "$1/System/man/lec" "$2/System/man"
cp "$1/System/bin/sudo" "$2/System/bin"
cp "$1/System/man/sudo" "$2/System/man"
